/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.*;

/**
 *
 * @author Eourist
 */
public class ListadoAfiliadosView extends javax.swing.JInternalFrame{
    AfiliadoData ad;
    DefaultTableModel tableModel;
    ArrayList<Afiliado> tablaMostrada;

    /**
     * Creates new form ListadoAfiliadosView
     */
    public ListadoAfiliadosView() {
        initComponents();
        ad = new AfiliadoData();
        tableModel = new DefaultTableModel();
        armarEncabezados();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtAfiliados = new javax.swing.JTable();
        jCheckBoxDeshabilitados = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Administracion de afiliados");

        jtAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtAfiliados);

        jCheckBoxDeshabilitados.setText("Mostrar inactivos");
        jCheckBoxDeshabilitados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxDeshabilitadosItemStateChanged(evt);
            }
        });
        jCheckBoxDeshabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDeshabilitadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jCheckBoxDeshabilitados)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxDeshabilitados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxDeshabilitadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxDeshabilitadosItemStateChanged
       llenarTabla();
    }//GEN-LAST:event_jCheckBoxDeshabilitadosItemStateChanged

    private void jCheckBoxDeshabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDeshabilitadosActionPerformed
       llenarTabla();
    }//GEN-LAST:event_jCheckBoxDeshabilitadosActionPerformed

    public void llenarTabla(){
        boolean activado = jCheckBoxDeshabilitados.isSelected();
        
        for (int i = tableModel.getRowCount(); i > 0; i--){
            tableModel.removeRow(i-1);
        }
        tablaMostrada = ad.obtenerAfiliados(activado);
            for (Afiliado a : tablaMostrada){
            tableModel.addRow(new Object[]{a.getDni(), a.getNombre(), (a.isActivo() ? "Si" : "No")});
            
        }
         
    }

    private void armarEncabezados(){
        ArrayList<Object> ob = new ArrayList<Object>();
        ob.add("DNI");
        ob.add("Nombre");
        ob.add("Activo");
        
        for(Object o : ob){
            tableModel.addColumn(o);
        }
        jtAfiliados.setModel(tableModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxDeshabilitados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAfiliados;
    // End of variables declaration//GEN-END:variables
}
